#!/usr/bin/env bash
# Transfer files from client to server
if [ $# -lt 3 ];
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp "$1" -i "$4" -o StrictHostKeyChecking=no "$3@$2":~/
fi
