#!/usr/bin/env bash
# script that transfert file from client to server
user=$3
ip_server=$2
f_path=$1
root=$user@$ip_server
if [ $# -lt 3 ];
then
echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -i "$4" -o StrictHostKeyCheking=no "$f_path" "$root" :~/
fi
