#!/usr/bin/env bash                                                          
# Install nginx web server                                                    
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
"Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/a add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx restart
