#!/usr/bin/env bash                                                          
# Install haproxy
apt-get -y update
apt-get -y install haproxy
echo -e "listen 1066-lb-01\n\tbind *:80\n\tstats enable\n\tbalance roundrobin\n\
\tserver 1066-web-01 34.73.0.225:80 check\n\tserver 1066-web-02 35.229.78.70:80\
 check" >> /etc/haproxy/haproxy.cfg
service haproxy start

