#!/usr/bin/env bash                                                          
# Install haproxy
sudo apt-get update
sudo apt-get -y install haproxy
echo "front webservers
     bind *:80
     mode http
     log global
     default_backend webservers" >> /etc/haproxy/haproxy.cfg
echo "backend webservers
      balance roundrobin
      server 1066-web-01 34.73.0.225:80 check
      server 1066-web-02 35.229.78.70:80 check" >> /etc/haproxy/haproxy.cfg
      sudo service haproxy restart
