#!/usr/bin/env bash
# Bash script
echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo I hate the kill command;
sudo rm /var/run/holbertonscript.pid; kill -9 $$' SIGQUIT SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while true
do
echo "To infinity and beyond"
sleep 2
done
